/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package security_1dv700_a1;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Menu menu = new Menu();
        menu.mainMenu();
        System.out.println(new App().getGreeting());

    }
}
